name: Create Zip File # created 'wc-ifudocs.zip' in repository

on:
  push:
    branches:
    - main

jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4


    - name: Generate ZIP
      uses: byteever/action-build-zip@master
      with:
        filename: 'wc-ifudocs.zip'